export const contracts = [
  {
    name: "cw721",
    path: ["contracts", "ixo", "cw721.wasm"],
    category: "ixo",
    code: { devnet: 1 },
  },
  {
    name: "ixo1155",
    path: ["contracts", "ixo", "ixo1155.wasm"],
    category: "ixo",
    code: { devnet: 2 },
  },
  {
    name: "dao_core",
    path: ["contracts", "daodao", "dao_core.wasm"],
    category: "daodao",
    code: { devnet: 3 },
  },
  {
    name: "cw_admin_factory",
    path: ["contracts", "daodao", "cw_admin_factory.wasm"],
    category: "daodao",
    code: { devnet: 4 },
  },
  {
    name: "cw_fund_distributor",
    path: ["contracts", "daodao", "cw_fund_distributor.wasm"],
    category: "daodao",
    code: { devnet: 5 },
  },
  {
    name: "cw_payroll_factory",
    path: ["contracts", "daodao", "cw_payroll_factory.wasm"],
    category: "daodao",
    code: { devnet: 6 },
  },
  {
    name: "cw_token_swap",
    path: ["contracts", "daodao", "cw_token_swap.wasm"],
    category: "daodao",
    code: { devnet: 7 },
  },
  {
    name: "cw_vesting",
    path: ["contracts", "daodao", "cw_vesting.wasm"],
    category: "daodao",
    code: { devnet: 8 },
  },
  {
    name: "dao_migrator",
    path: ["contracts", "daodao", "dao_migrator.wasm"],
    category: "daodao",
    code: { devnet: 9 },
  },
  {
    name: "dao_pre_propose_approval_single",
    path: ['contracts", "daodao", "dao_pre_propose_approval_singl.wasme'],
    category: "daodao",
    code: { devnet: 10 },
  },
  {
    name: "dao_pre_propose_approver",
    path: ["contracts", "daodao", "dao_pre_propose_approver.wasm"],
    category: "daodao",
    code: { devnet: 11 },
  },
  {
    name: "dao_pre_propose_multiple",
    path: ["contracts", "daodao", "dao_pre_propose_multiple.wasm"],
    category: "daodao",
    code: { devnet: 12 },
  },
  {
    name: "dao_pre_propose_single",
    path: ["contracts", "daodao", "dao_pre_propose_single.wasm"],
    category: "daodao",
    code: { devnet: 13 },
  },
  {
    name: "dao_proposal_condorcet",
    path: ["contracts", "daodao", "dao_proposal_condorcet.wasm"],
    category: "daodao",
    code: { devnet: 14 },
  },
  {
    name: "dao_proposal_multiple",
    path: ["contracts", "daodao", "dao_proposal_multiple.wasm"],
    category: "daodao",
    code: { devnet: 15 },
  },
  {
    name: "dao_proposal_single",
    path: ["contracts", "daodao", "dao_proposal_single.wasm"],
    category: "daodao",
    code: { devnet: 16 },
  },
  {
    name: "cw20_stake",
    path: ["contracts", "daodao", "cw20_stake.wasm"],
    category: "daodao",
    code: { devnet: 17 },
  },
  {
    name: "cw20_stake_external_rewards",
    path: ["contracts", "daodao", "cw20_stake_external_rewards.wasm"],
    category: "daodao",
    code: { devnet: 18 },
  },
  {
    name: "cw20_stake_reward_distributor",
    path: ['contracts", "daodao", "cw20_stake_reward_distributor.wasm'],
    category: "daodao",
    code: { devnet: 19 },
  },
  {
    name: "dao_voting_cw4",
    path: ["contracts", "daodao", "dao_voting_cw4.wasm"],
    category: "daodao",
    code: { devnet: 20 },
  },
  {
    name: "dao_voting_cw20_staked",
    path: ["contracts", "daodao", "dao_voting_cw20_staked.wasm"],
    category: "daodao",
    code: { devnet: 21 },
  },
  {
    name: "dao_voting_cw721_staked",
    path: ["contracts", "daodao", "dao_voting_cw721_staked.wasm"],
    category: "daodao",
    code: { devnet: 22 },
  },
  {
    name: "dao_voting_native_staked",
    path: ["contracts", "daodao", "dao_voting_native_staked.wasm"],
    category: "daodao",
    code: { devnet: 23 },
  },
  {
    name: "cw4_group",
    path: ["contracts", "cosmwasm", "cw4_group.wasm"],
    category: "daodao",
    code: { devnet: 24 },
  },
  {
    name: "cw20_base",
    path: ["contracts", "cosmwasm", "cw20_base.wasm"],
    category: "daodao",
    code: { devnet: 25 },
  },
  {
    name: "cw721_base",
    path: ["contracts", "cosmwasm", "cw721_base.wasm"],
    category: "daodao",
    code: { devnet: 26 },
  },
  {
    name: "wasmswap",
    path: ["contracts", "wasmswap", "wasmswap.wasm"],
    category: "daodao",
    code: { devnet: 27 },
  },
];
