export const contracts = [
  {
    name: "cw721",
    path: ["contracts", "ixo", "cw721.wasm"],
    category: "ixo",
    code: { devnet: 1, testnet: 1, mainnet: 1 },
  },
  {
    name: "ixo1155",
    path: ["contracts", "ixo", "ixo1155.wasm"],
    category: "ixo",
    code: { devnet: 2, testnet: 2, mainnet: 2 },
  },
  {
    name: "dao_core",
    path: ["contracts", "daodao", "dao_core.wasm"],
    category: "daodao",
    code: { devnet: 3, testnet: 3, mainnet: 3 },
  },
  {
    name: "cw_admin_factory",
    path: ["contracts", "daodao", "cw_admin_factory.wasm"],
    category: "daodao",
    code: { devnet: 4, testnet: 4, mainnet: 4 },
  },
  {
    name: "cw_fund_distributor",
    path: ["contracts", "daodao", "cw_fund_distributor.wasm"],
    category: "daodao",
    code: { devnet: 5, testnet: 5, mainnet: 5 },
  },
  {
    name: "cw_payroll_factory",
    path: ["contracts", "daodao", "cw_payroll_factory.wasm"],
    category: "daodao",
    code: { devnet: 6, testnet: 6, mainnet: 6 },
  },
  {
    name: "cw_token_swap",
    path: ["contracts", "daodao", "cw_token_swap.wasm"],
    category: "daodao",
    code: { devnet: 7, testnet: 7, mainnet: 7 },
  },
  {
    name: "cw_vesting",
    path: ["contracts", "daodao", "cw_vesting.wasm"],
    category: "daodao",
    code: { devnet: 8, testnet: 8, mainnet: 8 },
  },
  {
    name: "dao_migrator",
    path: ["contracts", "daodao", "dao_migrator.wasm"],
    category: "daodao",
    code: { devnet: 9, testnet: 9, mainnet: 9 },
  },
  {
    name: "dao_pre_propose_approval_single",
    path: ["contracts", "daodao", "dao_pre_propose_approval_single.wasm"],
    category: "daodao",
    code: { devnet: 10, testnet: 10, mainnet: 10 },
  },
  {
    name: "dao_pre_propose_approver",
    path: ["contracts", "daodao", "dao_pre_propose_approver.wasm"],
    category: "daodao",
    code: { devnet: 11, testnet: 11, mainnet: 11 },
  },
  {
    name: "dao_pre_propose_multiple",
    path: ["contracts", "daodao", "dao_pre_propose_multiple.wasm"],
    category: "daodao",
    code: { devnet: 12, testnet: 12, mainnet: 12 },
  },
  {
    name: "dao_pre_propose_single",
    path: ["contracts", "daodao", "dao_pre_propose_single.wasm"],
    category: "daodao",
    code: { devnet: 13, testnet: 13, mainnet: 13 },
  },
  {
    name: "dao_proposal_condorcet",
    path: ["contracts", "daodao", "dao_proposal_condorcet.wasm"],
    category: "daodao",
    code: { devnet: 14, testnet: 14, mainnet: 14 },
  },
  {
    name: "dao_proposal_multiple",
    path: ["contracts", "daodao", "dao_proposal_multiple.wasm"],
    category: "daodao",
    code: { devnet: 15, testnet: 15, mainnet: 15 },
  },
  {
    name: "dao_proposal_single",
    path: ["contracts", "daodao", "dao_proposal_single.wasm"],
    category: "daodao",
    code: { devnet: 16, testnet: 16, mainnet: 16 },
  },
  {
    name: "cw20_stake",
    path: ["contracts", "daodao", "cw20_stake.wasm"],
    category: "daodao",
    code: { devnet: 17, testnet: 17, mainnet: 17 },
  },
  {
    name: "cw20_stake_external_rewards",
    path: ["contracts", "daodao", "cw20_stake_external_rewards.wasm"],
    category: "daodao",
    code: { devnet: 18, testnet: 18, mainnet: 18 },
  },
  {
    name: "cw20_stake_reward_distributor",
    path: ["contracts", "daodao", "cw20_stake_reward_distributor.wasm"],
    category: "daodao",
    code: { devnet: 19, testnet: 19, mainnet: 19 },
  },
  {
    name: "dao_voting_cw4",
    path: ["contracts", "daodao", "dao_voting_cw4.wasm"],
    category: "daodao",
    code: { devnet: 20, testnet: 20, mainnet: 20 },
  },
  {
    name: "dao_voting_cw20_staked",
    path: ["contracts", "daodao", "dao_voting_cw20_staked.wasm"],
    category: "daodao",
    code: { devnet: 21, testnet: 21, mainnet: 21 },
  },
  {
    name: "dao_voting_cw721_staked",
    path: ["contracts", "daodao", "dao_voting_cw721_staked.wasm"],
    category: "daodao",
    code: { devnet: 22, testnet: 22, mainnet: 22 },
  },
  {
    name: "dao_voting_native_staked",
    path: ["contracts", "daodao", "dao_voting_native_staked.wasm"],
    category: "daodao",
    code: { devnet: 23, testnet: 23, mainnet: 23 },
  },
  {
    name: "cw4_group",
    path: ["contracts", "cosmwasm", "cw4_group.wasm"],
    category: "daodao",
    code: { devnet: 24, testnet: 24, mainnet: 24 },
  },
  {
    name: "cw20_base",
    path: ["contracts", "cosmwasm", "cw20_base.wasm"],
    category: "daodao",
    code: { devnet: 25, testnet: 25, mainnet: 25 },
  },
  {
    name: "cw721_base",
    path: ["contracts", "cosmwasm", "cw721_base.wasm"],
    category: "daodao",
    code: { devnet: 26, testnet: 26, mainnet: 26 },
  },
  {
    name: "wasmswap",
    path: ["contracts", "wasmswap", "wasmswap.wasm"],
    category: "daodao",
    code: { devnet: 27, testnet: 27, mainnet: 27 },
  },
  {
    name: "multicall",
    path: ["contracts", "custom", "multicall.wasm"],
    category: "ixo",
    code: { devnet: 28, testnet: 28, mainnet: 28 },
    address: {
      devnet: "ixo19zpp643ax9sf7zxzjswcfy03kqk4hrxjr9yt0u4skyl879vzhvuqgegng0",
      testnet: "ixo17hgwjxmz70ks6v5u2ay2maqf8anrpmleu0p4vyqw88s3sflwv7fqgz8j0f",
      mainnet: "ixo1d7d83gktpdlq0w0y0wtq6qd6yzp5jv744sz9dspluedvlxln23pq4ld8hc",
    },
  },
  {
    name: "ixoswap",
    path: ["contracts", "ixo", "ixoswap", "ixoswap.wasm"],
    category: "ixo",
    code: { devnet: 33, testnet: 31, mainnet: 30 },
  },
  {
    name: "hpl_hook_aggregate",
    path: ["contracts", "hyperlane", "hpl_hook_aggregate.wasm"],
    category: "hyperlane",
    code: { devnet: 49, testnet: 32, mainnet: 31 },
  },
  {
    name: "hpl_hook_fee",
    path: ["contracts", "hyperlane", "hpl_hook_fee.wasm"],
    category: "hyperlane",
    code: { devnet: 50, testnet: 33, mainnet: 32 },
  },
  {
    name: "hpl_hook_merkle",
    path: ["contracts", "hyperlane", "hpl_hook_merkle.wasm"],
    category: "hyperlane",
    code: { devnet: 51, testnet: 34, mainnet: 33 },
  },
  {
    name: "hpl_hook_pausable",
    path: ["contracts", "hyperlane", "hpl_hook_pausable.wasm"],
    category: "hyperlane",
    code: { devnet: 52, testnet: 35, mainnet: 34 },
  },
  {
    name: "hpl_hook_routing_custom",
    path: ["contracts", "hyperlane", "hpl_hook_routing_custom.wasm"],
    category: "hyperlane",
    code: { devnet: 53, testnet: 36, mainnet: 35 },
  },
  {
    name: "hpl_hook_routing_fallback",
    path: ["contracts", "hyperlane", "hpl_hook_routing_fallback.wasm"],
    category: "hyperlane",
    code: { devnet: 54, testnet: 37, mainnet: 36 },
  },
  {
    name: "hpl_hook_routing",
    path: ["contracts", "hyperlane", "hpl_hook_routing.wasm"],
    category: "hyperlane",
    code: { devnet: 55, testnet: 38, mainnet: 37 },
  },
  {
    name: "hpl_ism_pausable",
    path: ["contracts", "hyperlane", "hpl_ism_pausable.wasm"],
    category: "hyperlane",
    code: { devnet: 56, testnet: 39, mainnet: 38 },
  },
  {
    name: "hpl_validator_announce",
    path: ["contracts", "hyperlane", "hpl_validator_announce.wasm"],
    category: "hyperlane",
    code: { devnet: 57, testnet: 40, mainnet: 39 },
  },
  {
    name: "hpl_igp_oracle",
    path: ["contracts", "hyperlane", "hpl_igp_oracle.wasm"],
    category: "hyperlane",
    code: { devnet: 58, testnet: 41, mainnet: 40 },
  },
  {
    name: "hpl_ism_aggregate",
    path: ["contracts", "hyperlane", "hpl_ism_aggregate.wasm"],
    category: "hyperlane",
    code: { devnet: 59, testnet: 42, mainnet: 41 },
  },
  {
    name: "hpl_ism_multisig",
    path: ["contracts", "hyperlane", "hpl_ism_multisig.wasm"],
    category: "hyperlane",
    code: { devnet: 60, testnet: 43, mainnet: 42 },
  },
  {
    name: "hpl_ism_routing",
    path: ["contracts", "hyperlane", "hpl_ism_routing.wasm"],
    category: "hyperlane",
    code: { devnet: 61, testnet: 44, mainnet: 43 },
  },
  {
    name: "hpl_mailbox",
    path: ["contracts", "hyperlane", "hpl_mailbox.wasm"],
    category: "hyperlane",
    code: { devnet: 62, testnet: 45, mainnet: 44 },
  },
  {
    name: "hpl_test_mock_hook",
    path: ["contracts", "hyperlane", "hpl_test_mock_hook.wasm"],
    category: "hyperlane",
    code: { devnet: 63, testnet: 46, mainnet: 45 },
  },
  {
    name: "hpl_test_mock_ism",
    path: ["contracts", "hyperlane", "hpl_test_mock_ism.wasm"],
    category: "hyperlane",
    code: { devnet: 64, testnet: 47, mainnet: 46 },
  },
  {
    name: "hpl_test_mock_msg_receiver",
    path: ["contracts", "hyperlane", "hpl_test_mock_msg_receiver.wasm"],
    category: "hyperlane",
    code: { devnet: 65, testnet: 48, mainnet: 47 },
  },
  {
    name: "hpl_warp_native",
    path: ["contracts", "hyperlane", "hpl_warp_native.wasm"],
    category: "hyperlane",
    code: { devnet: 66, testnet: 49, mainnet: 48 },
  },
  {
    name: "hpl_warp_cw20",
    path: ["contracts", "hyperlane", "hpl_warp_cw20.wasm"],
    category: "hyperlane",
    code: { devnet: 67, testnet: 50, mainnet: 49 },
  },
  {
    name: "hpl_igp",
    path: ["contracts", "hyperlane", "hpl_igp.wasm"],
    category: "hyperlane",
    code: { devnet: 68, testnet: 51, mainnet: 50 },
  },
];
