export const keplrCurrencies = {
  ubld: {
    coinDenom: "BLD",
    coinMinimalDenom: "ubld",
    coinDecimals: 6,
    coinGeckoId: "agoric",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/agoric/chain.png",
  },
  uist: {
    coinDenom: "IST",
    coinMinimalDenom: "uist",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  uakt: {
    coinDenom: "AKT",
    coinMinimalDenom: "uakt",
    coinDecimals: 6,
    coinGeckoId: "akash-network",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/akashnet/chain.png",
  },
  uaxl: {
    coinDenom: "AXL",
    coinMinimalDenom: "uaxl",
    coinDecimals: 6,
    coinGeckoId: "axelar",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/axelar-dojo/chain.png",
  },
  "weth-wei": {
    coinDenom: "WETH",
    coinMinimalDenom: "weth-wei",
    coinDecimals: 18,
    coinGeckoId: "weth",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uusdc: {
    coinDenom: "USDC",
    coinMinimalDenom: "uusdc",
    coinDecimals: 6,
    coinGeckoId: "usd-coin",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "frax-wei": {
    coinDenom: "FRAX",
    coinMinimalDenom: "frax-wei",
    coinDecimals: 18,
    coinGeckoId: "frax",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "dai-wei": {
    coinDenom: "DAI",
    coinMinimalDenom: "dai-wei",
    coinDecimals: 18,
    coinGeckoId: "dai",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uusdt: {
    coinDenom: "USDT",
    coinMinimalDenom: "uusdt",
    coinDecimals: 6,
    coinGeckoId: "tether",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "wbtc-satoshi": {
    coinDenom: "WBTC",
    coinMinimalDenom: "wbtc-satoshi",
    coinDecimals: 8,
    coinGeckoId: "wrapped-bitcoin",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "link-wei": {
    coinDenom: "LINK",
    coinMinimalDenom: "link-wei",
    coinDecimals: 18,
    coinGeckoId: "chainlink",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "aave-wei": {
    coinDenom: "AAVE",
    coinMinimalDenom: "aave-wei",
    coinDecimals: 18,
    coinGeckoId: "aave",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "ape-wei": {
    coinDenom: "APE",
    coinMinimalDenom: "ape-wei",
    coinDecimals: 18,
    coinGeckoId: "apecoin",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "axs-wei": {
    coinDenom: "AXS",
    coinMinimalDenom: "axs-wei",
    coinDecimals: 18,
    coinGeckoId: "axie-infinity",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "mkr-wei": {
    coinDenom: "MKR",
    coinMinimalDenom: "mkr-wei",
    coinDecimals: 18,
    coinGeckoId: "maker",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "rai-wei": {
    coinDenom: "RAI",
    coinMinimalDenom: "rai-wei",
    coinDecimals: 18,
    coinGeckoId: "rai",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "shib-wei": {
    coinDenom: "SHIB",
    coinMinimalDenom: "shib-wei",
    coinDecimals: 18,
    coinGeckoId: "shiba-inu",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "steth-wei": {
    coinDenom: "stETH",
    coinMinimalDenom: "steth-wei",
    coinDecimals: 18,
    coinGeckoId: "staked-ether",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "uni-wei": {
    coinDenom: "UNI",
    coinMinimalDenom: "uni-wei",
    coinDecimals: 18,
    coinGeckoId: "uniswap",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "xcn-wei": {
    coinDenom: "XCN",
    coinMinimalDenom: "xcn-wei",
    coinDecimals: 18,
    coinGeckoId: "chain-2",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "wglmr-wei": {
    coinDenom: "WGLMR",
    coinMinimalDenom: "wglmr-wei",
    coinDecimals: 18,
    coinGeckoId: "wrapped-moonbeam",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  "dot-planck": {
    coinDenom: "DOT",
    coinMinimalDenom: "dot-planck",
    coinDecimals: 10,
    coinGeckoId: "polkadot",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ubcna: {
    coinDenom: "BCNA",
    coinMinimalDenom: "ubcna",
    coinDecimals: 6,
    coinGeckoId: "bitcanna",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/bitcanna/chain.png",
  },
  boot: {
    coinDenom: "BOOT",
    coinMinimalDenom: "boot",
    coinDecimals: 0,
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/bostrom/chain.png",
  },
  hydrogen: {
    coinDenom: "H",
    coinMinimalDenom: "hydrogen",
    coinDecimals: 0,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  millivolt: {
    coinDenom: "V",
    coinMinimalDenom: "millivolt",
    coinDecimals: 3,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  milliampere: {
    coinDenom: "A",
    coinMinimalDenom: "milliampere",
    coinDecimals: 3,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  tocyb: {
    coinDenom: "TOCYB",
    coinMinimalDenom: "tocyb",
    coinDecimals: 0,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  swth: {
    coinDenom: "SWTH",
    coinMinimalDenom: "swth",
    coinDecimals: 8,
    coinGeckoId: "switcheo",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/carbon/chain.png",
  },
  "bnb.1.6.773edb": {
    coinDenom: "BNB",
    coinMinimalDenom: "bnb.1.6.773edb",
    coinDecimals: 18,
    coinGeckoId: "binancecoin",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  bneo: {
    coinDenom: "bNEO",
    coinMinimalDenom: "bneo",
    coinDecimals: 8,
    coinGeckoId: "neo",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "bneo.1.14.e2e5f6": {
    coinDenom: "bNEO",
    coinMinimalDenom: "bneo.1.14.e2e5f6",
    coinDecimals: 8,
    coinGeckoId: "neo",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "busd.1.6.754a80": {
    coinDenom: "BUSD",
    coinMinimalDenom: "busd.1.6.754a80",
    coinDecimals: 18,
    coinGeckoId: "binance-usd",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  eth: {
    coinDenom: "ETH",
    coinMinimalDenom: "eth",
    coinDecimals: 18,
    coinGeckoId: "ethereum",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "eth.1.19.c3b805": {
    coinDenom: "ETH",
    coinMinimalDenom: "eth.1.19.c3b805",
    coinDecimals: 18,
    coinGeckoId: "ethereum",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "eth.1.2.942d87": {
    coinDenom: "ETH",
    coinMinimalDenom: "eth.1.2.942d87",
    coinDecimals: 18,
    coinGeckoId: "ethereum",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  usc: {
    coinDenom: "USC",
    coinMinimalDenom: "usc",
    coinDecimals: 6,
    coinGeckoId: "carbon-usd",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  usdc: {
    coinDenom: "USDC",
    coinMinimalDenom: "usdc",
    coinDecimals: 6,
    coinGeckoId: "usd-coin",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "usdc.1.2.343151": {
    coinDenom: "USDC",
    coinMinimalDenom: "usdc.1.2.343151",
    coinDecimals: 6,
    coinGeckoId: "usd-coin",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "usdc.1.6.53ff75": {
    coinDenom: "USDC",
    coinMinimalDenom: "usdc.1.6.53ff75",
    coinDecimals: 18,
    coinGeckoId: "usd-coin",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  "cgt/1": {
    coinDenom: "USD",
    coinMinimalDenom: "cgt/1",
    coinDecimals: 18,
    coinGeckoId: "usd-coin",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  uhuahua: {
    coinDenom: "HUAHUA",
    coinMinimalDenom: "uhuahua",
    coinDecimals: 6,
    coinGeckoId: "chihuahua-token",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/chihuahua/chain.png",
  },
  ucmdx: {
    coinDenom: "CMDX",
    coinMinimalDenom: "ucmdx",
    coinDecimals: 6,
    coinGeckoId: "comdex",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/comdex/chain.png",
  },
  ucmst: {
    coinDenom: "CMST",
    coinMinimalDenom: "ucmst",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uharbor: {
    coinDenom: "HARBOR",
    coinMinimalDenom: "uharbor",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uatom: {
    coinDecimals: 6,
    coinDenom: "ATOM",
    coinGeckoId: "cosmos",
    coinMinimalDenom: "uatom",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/cosmoshub/chain.png",
  },
  ucre: {
    coinDenom: "CRE",
    coinMinimalDenom: "ucre",
    coinDecimals: 6,
    coinGeckoId: "crescent-network",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/crescent/chain.png",
  },
  ubcre: {
    coinDenom: "bCRE",
    coinMinimalDenom: "ubcre",
    coinDecimals: 6,
    coinGeckoId: "liquid-staking-crescent",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  basecro: {
    coinDenom: "CRO",
    coinMinimalDenom: "basecro",
    coinDecimals: 8,
    coinGeckoId: "crypto-com-chain",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/crypto-org-chain-mainnet/chain.png",
  },
  udsm: {
    coinDenom: "DSM",
    coinMinimalDenom: "udsm",
    coinDecimals: 6,
    coinGeckoId: "desmos",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/desmos-mainnet/chain.png",
  },
  ungm: {
    coinDenom: "NGM",
    coinMinimalDenom: "ungm",
    coinDecimals: 6,
    coinGeckoId: "e-money",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/emoney/chain.png",
  },
  eeur: {
    coinDenom: "EEUR",
    coinMinimalDenom: "eeur",
    coinDecimals: 6,
    coinGeckoId: "e-money-eur",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  edkk: {
    coinDenom: "EDKK",
    coinMinimalDenom: "edkk",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  esek: {
    coinDenom: "ESEK",
    coinMinimalDenom: "esek",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  enok: {
    coinDenom: "ENOK",
    coinMinimalDenom: "enok",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  echf: {
    coinDenom: "ECHF",
    coinMinimalDenom: "echf",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  aevmos: {
    coinDenom: "EVMOS",
    coinMinimalDenom: "aevmos",
    coinDecimals: 18,
    coinGeckoId: "evmos",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/evmos_9001/chain.png",
  },
  ufct: {
    coinDenom: "FCT",
    coinMinimalDenom: "ufct",
    coinDecimals: 6,
    coinGeckoId: "firmachain",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/colosseum/chain.png",
  },
  ugraviton: {
    coinDenom: "GRAV",
    coinMinimalDenom: "ugraviton",
    coinDecimals: 6,
    coinGeckoId: "graviton",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/gravity-bridge/chain.png",
  },
  uixo: {
    coinDenom: "IXO",
    coinMinimalDenom: "uixo",
    coinDecimals: 6,
    coinGeckoId: "ixo",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/ixo/chain.png",
  },
  inj: {
    coinDenom: "INJ",
    coinDecimals: 18,
    coinMinimalDenom: "inj",
    coinGeckoId: "injective-protocol",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/injective/chain.png",
  },
  uiris: {
    coinDenom: "IRIS",
    coinMinimalDenom: "uiris",
    coinDecimals: 6,
    coinGeckoId: "iris-network",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/irishub/chain.png",
  },
  ujkl: {
    coinDenom: "JKL",
    coinMinimalDenom: "ujkl",
    coinDecimals: 6,
    coinGeckoId: "jackal-protocol",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/jackal/chain.png",
  },
  ujuno: {
    coinDenom: "JUNO",
    coinMinimalDenom: "ujuno",
    coinDecimals: 6,
    coinGeckoId: "juno-network",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/juno/chain.png",
  },
  ukava: {
    coinDenom: "KAVA",
    coinMinimalDenom: "ukava",
    coinDecimals: 6,
    coinGeckoId: "kava",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/kava_2222/chain.png",
  },
  swp: {
    coinDenom: "SWP",
    coinMinimalDenom: "swp",
    coinDecimals: 6,
    coinGeckoId: "kava-swap",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  usdx: {
    coinDenom: "USDX",
    coinMinimalDenom: "usdx",
    coinDecimals: 6,
    coinGeckoId: "usdx",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  hard: {
    coinDenom: "HARD",
    coinMinimalDenom: "hard",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  bnb: {
    coinDenom: "BNB",
    coinMinimalDenom: "bnb",
    coinDecimals: 8,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  btcb: {
    coinDenom: "BTCB",
    coinMinimalDenom: "btcb",
    coinDecimals: 8,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  busd: {
    coinDenom: "BUSD",
    coinMinimalDenom: "busd",
    coinDecimals: 8,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  xrpb: {
    coinDenom: "XRPB",
    coinMinimalDenom: "xrpb",
    coinDecimals: 8,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  nanolike: {
    coinDenom: "LIKE",
    coinMinimalDenom: "nanolike",
    coinDecimals: 9,
    coinGeckoId: "likecoin",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/likecoin-mainnet/chain.png",
  },
  ulum: {
    coinDenom: "LUM",
    coinMinimalDenom: "ulum",
    coinDecimals: 6,
    coinGeckoId: "lum-network",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/lum-network/chain.png",
  },
  udfr: {
    coinDenom: "DFR",
    coinMinimalDenom: "udfr",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  umars: {
    coinDenom: "MARS",
    coinMinimalDenom: "umars",
    coinDecimals: 6,
    coinGeckoId: "mars-protocol-a7fcbcfb-fd61-4017-92f0-7ee9f9cc6da3",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/mars/chain.png",
  },
  umedas: {
    coinDenom: "MEDAS",
    coinMinimalDenom: "umedas",
    coinDecimals: 6,
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/medasdigital/chain.png",
  },
  umeme: {
    coinDenom: "MEME",
    coinMinimalDenom: "umeme",
    coinDecimals: 6,
    coinGeckoId: "meme-netowrk",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/meme/chain.png",
  },
  unym: {
    coinDenom: "NYM",
    coinMinimalDenom: "unym",
    coinDecimals: 6,
    coinGeckoId: "nym",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  unyx: {
    coinDenom: "NYX",
    coinMinimalDenom: "unyx",
    coinDecimals: 6,
    coinGeckoId: "nyx",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/nyx/chain.png",
  },
  uflix: {
    coinDenom: "FLIX",
    coinMinimalDenom: "uflix",
    coinDecimals: 6,
    coinGeckoId: "omniflix-network",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/omniflixhub/chain.png",
  },
  uosmo: {
    coinDenom: "OSMO",
    coinMinimalDenom: "uosmo",
    coinDecimals: 6,
    coinGeckoId: "osmosis",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/osmosis/chain.png",
  },
  uion: {
    coinDenom: "ION",
    coinMinimalDenom: "uion",
    coinDecimals: 6,
    coinGeckoId: "ion",
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uxprt: {
    coinDenom: "XPRT",
    coinMinimalDenom: "uxprt",
    coinDecimals: 6,
    coinGeckoId: "persistence",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/core/chain.png",
  },
  "stk/uatom": {
    coinDenom: "STKATOM",
    coinMinimalDenom: "stk/uatom",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  nhash: {
    coinDecimals: 9,
    coinDenom: "HASH",
    coinGeckoId: "provenance-blockchain",
    coinMinimalDenom: "nhash",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/pio-mainnet/chain.png",
  },
  uqck: {
    coinDenom: "QCK",
    coinMinimalDenom: "uqck",
    coinDecimals: 6,
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/quicksilver/chain.png",
  },
  uqstars: {
    coinDenom: "qSTARS",
    coinMinimalDenom: "uqstars",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uqatom: {
    coinDenom: "qATOM",
    coinMinimalDenom: "uqatom",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uqregen: {
    coinDenom: "qREGEN",
    coinMinimalDenom: "uqregen",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uregen: {
    coinDenom: "REGEN",
    coinMinimalDenom: "uregen",
    coinDecimals: 6,
    coinGeckoId: "regen",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/regen/chain.png",
  },
  uscrt: {
    coinDenom: "SCRT",
    coinMinimalDenom: "uscrt",
    coinDecimals: 6,
    coinGeckoId: "secret",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/secret/chain.png",
  },
  udvpn: {
    coinDenom: "DVPN",
    coinMinimalDenom: "udvpn",
    coinDecimals: 6,
    coinGeckoId: "sentinel",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/sentinelhub/chain.png",
  },
  uctk: {
    coinDenom: "CTK",
    coinMinimalDenom: "uctk",
    coinDecimals: 6,
    coinGeckoId: "certik",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/shentu-2.2/chain.png",
  },
  rowan: {
    coinDenom: "ROWAN",
    coinMinimalDenom: "rowan",
    coinDecimals: 18,
    coinGeckoId: "sifchain",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/sifchain/chain.png",
  },
  cusdt: {
    coinDenom: "Tether USDT",
    coinMinimalDenom: "cusdt",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ceth: {
    coinDenom: "Ethereum",
    coinMinimalDenom: "ceth",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cbat: {
    coinDenom: "Basic Attention Token",
    coinMinimalDenom: "cbat",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cant: {
    coinDenom: "Aragon",
    coinMinimalDenom: "cant",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cbnt: {
    coinDenom: "Bancor Network Token",
    coinMinimalDenom: "cbnt",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  czrx: {
    coinDenom: "0x",
    coinMinimalDenom: "czrx",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  clink: {
    coinDenom: "Chainlink",
    coinMinimalDenom: "clink",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cmana: {
    coinDenom: "Decentraland",
    coinMinimalDenom: "cmana",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  clrc: {
    coinDenom: "Loopring",
    coinMinimalDenom: "clrc",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cenj: {
    coinDenom: "Enjin Coin",
    coinMinimalDenom: "cenj",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csnx: {
    coinDenom: "Synthetix Network Token",
    coinMinimalDenom: "csnx",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ctusd: {
    coinDenom: "TrueUSD",
    coinMinimalDenom: "ctusd",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cocean: {
    coinDenom: "Ocean Protocol",
    coinMinimalDenom: "cocean",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cftm: {
    coinDenom: "Fantom",
    coinMinimalDenom: "cftm",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csusd: {
    coinDenom: "sUSD",
    coinMinimalDenom: "csusd",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cusdc: {
    coinDenom: "USD Coin",
    coinMinimalDenom: "cusdc",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ccro: {
    coinDenom: "Crypto com Coin",
    coinMinimalDenom: "ccro",
    coinDecimals: 8,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cwbtc: {
    coinDenom: "Wrapped Bitcoin",
    coinMinimalDenom: "cwbtc",
    coinDecimals: 8,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csxp: {
    coinDenom: "Swipe",
    coinMinimalDenom: "csxp",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cband: {
    coinDenom: "Band Protocol",
    coinMinimalDenom: "cband",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cdai: {
    coinDenom: "Dai Stablecoin",
    coinMinimalDenom: "cdai",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ccomp: {
    coinDenom: "Compound",
    coinMinimalDenom: "ccomp",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cuma: {
    coinDenom: "UMA",
    coinMinimalDenom: "cuma",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cbal: {
    coinDenom: "Balancer",
    coinMinimalDenom: "cbal",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cyfi: {
    coinDenom: "Yearn finance",
    coinMinimalDenom: "cyfi",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csrm: {
    coinDenom: "Serum",
    coinMinimalDenom: "csrm",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ccream: {
    coinDenom: "Cream",
    coinMinimalDenom: "ccream",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csand: {
    coinDenom: "SAND",
    coinMinimalDenom: "csand",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csushi: {
    coinDenom: "Sushi",
    coinMinimalDenom: "csushi",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cesd: {
    coinDenom: "Empty Set Dollar",
    coinMinimalDenom: "cesd",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cuni: {
    coinDenom: "Uniswap",
    coinMinimalDenom: "cuni",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  caave: {
    coinDenom: "Aave",
    coinMinimalDenom: "caave",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cbond: {
    coinDenom: "BarnBridge",
    coinMinimalDenom: "cbond",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cwfil: {
    coinDenom: "Wrapped Filecoin",
    coinMinimalDenom: "cwfil",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cgrt: {
    coinDenom: "The Graph",
    coinMinimalDenom: "cgrt",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  clon: {
    coinDenom: "Tokenlon",
    coinMinimalDenom: "clon",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  c1inch: {
    coinDenom: "1inch",
    coinMinimalDenom: "c1inch",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  crune: {
    coinDenom: "THORChain ERC20",
    coinMinimalDenom: "crune",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cwscrt: {
    coinDenom: "Secret ERC20",
    coinMinimalDenom: "cwscrt",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ciotx: {
    coinDenom: "IoTeX",
    coinMinimalDenom: "ciotx",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  creef: {
    coinDenom: "Reef Finance",
    coinMinimalDenom: "creef",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ccocos: {
    coinDenom: "COCOS BCX",
    coinMinimalDenom: "ccocos",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ckeep: {
    coinDenom: "Keep Network",
    coinMinimalDenom: "ckeep",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cogn: {
    coinDenom: "Origin Protocol",
    coinMinimalDenom: "cogn",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cdaofi: {
    coinDenom: "ODAOfi",
    coinMinimalDenom: "cdaofi",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  clina: {
    coinDenom: "Linear",
    coinMinimalDenom: "clina",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ctshp: {
    coinDenom: "12Ships",
    coinMinimalDenom: "ctshp",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cb20: {
    coinDenom: "B.20",
    coinMinimalDenom: "cb20",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cakro: {
    coinDenom: "Akropolis",
    coinMinimalDenom: "cakro",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  crfuel: {
    coinDenom: "Rio Fuel Token",
    coinMinimalDenom: "crfuel",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  crly: {
    coinDenom: "Rally",
    coinMinimalDenom: "crly",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cconv: {
    coinDenom: "Convergence",
    coinMinimalDenom: "cconv",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  crndr: {
    coinDenom: "Render Token",
    coinMinimalDenom: "crndr",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cpaid: {
    coinDenom: "PAID Network",
    coinMinimalDenom: "cpaid",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ctidal: {
    coinDenom: "Tidal",
    coinMinimalDenom: "ctidal",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  caxs: {
    coinDenom: "Axie Infinity",
    coinMinimalDenom: "caxs",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cbtsg: {
    coinDenom: "BitSong",
    coinMinimalDenom: "cbtsg",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ccsms: {
    coinDenom: "Cosmostarter",
    coinMinimalDenom: "ccsms",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cdfyn: {
    coinDenom: "Dfyn Network",
    coinMinimalDenom: "cdfyn",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cdino: {
    coinDenom: "DinoSwap",
    coinMinimalDenom: "cdino",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cdnxc: {
    coinDenom: "DinoX",
    coinMinimalDenom: "cdnxc",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cdon: {
    coinDenom: "Don-key",
    coinMinimalDenom: "cdon",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cern: {
    coinDenom: "Ethernity Chain",
    coinMinimalDenom: "cern",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cfrax: {
    coinDenom: "Frax",
    coinMinimalDenom: "cfrax",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cfxs: {
    coinDenom: "Frax Share",
    coinMinimalDenom: "cfxs",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ckft: {
    coinDenom: "Knit Finance",
    coinMinimalDenom: "ckft",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cldo: {
    coinDenom: "Lido DAO",
    coinMinimalDenom: "cldo",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cleash: {
    coinDenom: "Doge Killer",
    coinMinimalDenom: "cleash",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  clgcy: {
    coinDenom: "LGCY Network",
    coinMinimalDenom: "clgcy",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cmatic: {
    coinDenom: "Polygon",
    coinMinimalDenom: "cmatic",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cmetis: {
    coinDenom: "Metis Token",
    coinMinimalDenom: "cmetis",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  coh: {
    coinDenom: "Oh! Finance",
    coinMinimalDenom: "coh",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cpols: {
    coinDenom: "Polkastarter",
    coinMinimalDenom: "cpols",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cpond: {
    coinDenom: "Marlin",
    coinMinimalDenom: "cpond",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cquick: {
    coinDenom: "Quickswap",
    coinMinimalDenom: "cquick",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  crail: {
    coinDenom: "Railgun",
    coinMinimalDenom: "crail",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cratom: {
    coinDenom: "StaFi rATOM",
    coinMinimalDenom: "cratom",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  csaito: {
    coinDenom: "Saito",
    coinMinimalDenom: "csaito",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cshib: {
    coinDenom: "Shiba Inu",
    coinMinimalDenom: "cshib",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ctoke: {
    coinDenom: "Tokemak",
    coinMinimalDenom: "ctoke",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cufo: {
    coinDenom: "UFO Gaming",
    coinMinimalDenom: "cufo",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  cust: {
    coinDenom: "UST (ERC-20)",
    coinMinimalDenom: "cust",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  czcn: {
    coinDenom: "0chain",
    coinMinimalDenom: "czcn",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  czcx: {
    coinDenom: "Unizen",
    coinMinimalDenom: "czcx",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  usomm: {
    coinDenom: "SOMM",
    coinMinimalDenom: "usomm",
    coinDecimals: 6,
    coinGeckoId: "sommelier",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/sommelier/chain.png",
  },
  ufis: {
    coinDenom: "FIS",
    coinMinimalDenom: "ufis",
    coinDecimals: 6,
    coinGeckoId: "stafi",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/stafihub/chain.png",
  },
  uratom: {
    coinDenom: "rATOM",
    coinMinimalDenom: "uratom",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uriris: {
    coinDenom: "rIRIS",
    coinMinimalDenom: "uriris",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  urhuahua: {
    coinDenom: "rHUAHUA",
    coinMinimalDenom: "urhuahua",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  ustars: {
    coinDenom: "STARS",
    coinMinimalDenom: "ustars",
    coinDecimals: 6,
    coinGeckoId: "stargaze",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/stargaze/chain.png",
  },
  uiov: {
    coinDenom: "IOV",
    coinMinimalDenom: "uiov",
    coinDecimals: 6,
    coinGeckoId: "starname",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/iov-mainnet-ibc/chain.png",
  },
  ustrd: {
    coinDenom: "STRD",
    coinMinimalDenom: "ustrd",
    coinDecimals: 6,
    coinGeckoId: "stride",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/stride/chain.png",
  },
  stuatom: {
    coinDenom: "stATOM",
    coinMinimalDenom: "stuatom",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  stuosmo: {
    coinDenom: "stOSMO",
    coinMinimalDenom: "stuosmo",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  stujuno: {
    coinDenom: "stJUNO",
    coinMinimalDenom: "stujuno",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  stustars: {
    coinDenom: "stSTARS",
    coinMinimalDenom: "stustars",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  staevmos: {
    coinDenom: "stEVMOS",
    coinMinimalDenom: "staevmos",
    coinDecimals: 18,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  stuluna: {
    coinDenom: "stLUNA",
    coinMinimalDenom: "stuluna",
    coinDecimals: 6,
    isStakeCurrency: false,
    isFeeCurrency: false,
  },
  uluna: {
    coinDenom: "LUNA",
    coinMinimalDenom: "uluna",
    coinDecimals: 6,
    coinGeckoId: "terra-luna-2",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/phoenix/chain.png",
  },
  uusd: {
    coinDenom: "USTC",
    coinMinimalDenom: "uusd",
    coinDecimals: 6,
    coinGeckoId: "terrausd",
    isStakeCurrency: false,
    isFeeCurrency: true,
  },
  utgd: {
    coinDenom: "TGD",
    coinMinimalDenom: "utgd",
    coinDecimals: 6,
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/tgrade-mainnet/chain.png",
  },
  uumee: {
    coinDenom: "UMEE",
    coinMinimalDenom: "uumee",
    coinDecimals: 6,
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/umee/chain.png",
  },
  nund: {
    coinDenom: "FUND",
    coinMinimalDenom: "nund",
    coinDecimals: 9,
    coinGeckoId: "unification",
    isStakeCurrency: true,
    isFeeCurrency: true,
    coinImageUrl:
      "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/FUND-MainNet/chain.png",
  },
};
