/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./DaoCore.client";
import * as _3 from "./CwAdminFactory.client";
import * as _5 from "./CwFundDistributor.client";
import * as _7 from "./CwPayrollFactory.client";
import * as _9 from "./CwTokenSwap.client";
import * as _11 from "./CwVesting.client";
import * as _13 from "./DaoMigrator.client";
import * as _15 from "./DaoPreProposeApprovalSingle.client";
import * as _17 from "./DaoPreProposeApprover.client";
import * as _19 from "./DaoPreProposeMultiple.client";
import * as _21 from "./DaoPreProposeSingle.client";
import * as _23 from "./DaoProposalCondorcet.client";
import * as _25 from "./DaoProposalMultiple.client";
import * as _27 from "./DaoProposalSingle.client";
import * as _29 from "./Cw20Stake.client";
import * as _31 from "./Cw20StakeExternalRewards.client";
import * as _33 from "./Cw20StakeRewardDistributor.client";
import * as _35 from "./DaoVotingCw4.client";
import * as _37 from "./DaoVotingCw20Staked.client";
import * as _39 from "./DaoVotingCw721Staked.client";
import * as _41 from "./DaoVotingNativeStaked.client";
export declare namespace contracts {
    const DaoCore: {
        DaoCoreQueryClient: typeof _1.DaoCoreQueryClient;
        DaoCoreClient: typeof _1.DaoCoreClient;
    };
    const CwAdminFactory: {
        CwAdminFactoryQueryClient: typeof _3.CwAdminFactoryQueryClient;
        CwAdminFactoryClient: typeof _3.CwAdminFactoryClient;
    };
    const CwFundDistributor: {
        CwFundDistributorQueryClient: typeof _5.CwFundDistributorQueryClient;
        CwFundDistributorClient: typeof _5.CwFundDistributorClient;
    };
    const CwPayrollFactory: {
        CwPayrollFactoryQueryClient: typeof _7.CwPayrollFactoryQueryClient;
        CwPayrollFactoryClient: typeof _7.CwPayrollFactoryClient;
    };
    const CwTokenSwap: {
        CwTokenSwapQueryClient: typeof _9.CwTokenSwapQueryClient;
        CwTokenSwapClient: typeof _9.CwTokenSwapClient;
    };
    const CwVesting: {
        CwVestingQueryClient: typeof _11.CwVestingQueryClient;
        CwVestingClient: typeof _11.CwVestingClient;
    };
    const DaoMigrator: {
        DaoMigratorQueryClient: typeof _13.DaoMigratorQueryClient;
        DaoMigratorClient: typeof _13.DaoMigratorClient;
    };
    const DaoPreProposeApprovalSingle: {
        DaoPreProposeApprovalSingleQueryClient: typeof _15.DaoPreProposeApprovalSingleQueryClient;
        DaoPreProposeApprovalSingleClient: typeof _15.DaoPreProposeApprovalSingleClient;
    };
    const DaoPreProposeApprover: {
        DaoPreProposeApproverQueryClient: typeof _17.DaoPreProposeApproverQueryClient;
        DaoPreProposeApproverClient: typeof _17.DaoPreProposeApproverClient;
    };
    const DaoPreProposeMultiple: {
        DaoPreProposeMultipleQueryClient: typeof _19.DaoPreProposeMultipleQueryClient;
        DaoPreProposeMultipleClient: typeof _19.DaoPreProposeMultipleClient;
    };
    const DaoPreProposeSingle: {
        DaoPreProposeSingleQueryClient: typeof _21.DaoPreProposeSingleQueryClient;
        DaoPreProposeSingleClient: typeof _21.DaoPreProposeSingleClient;
    };
    const DaoProposalCondorcet: {
        DaoProposalCondorcetQueryClient: typeof _23.DaoProposalCondorcetQueryClient;
        DaoProposalCondorcetClient: typeof _23.DaoProposalCondorcetClient;
    };
    const DaoProposalMultiple: {
        DaoProposalMultipleQueryClient: typeof _25.DaoProposalMultipleQueryClient;
        DaoProposalMultipleClient: typeof _25.DaoProposalMultipleClient;
    };
    const DaoProposalSingle: {
        DaoProposalSingleQueryClient: typeof _27.DaoProposalSingleQueryClient;
        DaoProposalSingleClient: typeof _27.DaoProposalSingleClient;
    };
    const Cw20Stake: {
        Cw20StakeQueryClient: typeof _29.Cw20StakeQueryClient;
        Cw20StakeClient: typeof _29.Cw20StakeClient;
    };
    const Cw20StakeExternalRewards: {
        Cw20StakeExternalRewardsQueryClient: typeof _31.Cw20StakeExternalRewardsQueryClient;
        Cw20StakeExternalRewardsClient: typeof _31.Cw20StakeExternalRewardsClient;
    };
    const Cw20StakeRewardDistributor: {
        Cw20StakeRewardDistributorQueryClient: typeof _33.Cw20StakeRewardDistributorQueryClient;
        Cw20StakeRewardDistributorClient: typeof _33.Cw20StakeRewardDistributorClient;
    };
    const DaoVotingCw4: {
        DaoVotingCw4QueryClient: typeof _35.DaoVotingCw4QueryClient;
        DaoVotingCw4Client: typeof _35.DaoVotingCw4Client;
    };
    const DaoVotingCw20Staked: {
        DaoVotingCw20StakedQueryClient: typeof _37.DaoVotingCw20StakedQueryClient;
        DaoVotingCw20StakedClient: typeof _37.DaoVotingCw20StakedClient;
    };
    const DaoVotingCw721Staked: {
        DaoVotingCw721StakedQueryClient: typeof _39.DaoVotingCw721StakedQueryClient;
        DaoVotingCw721StakedClient: typeof _39.DaoVotingCw721StakedClient;
    };
    const DaoVotingNativeStaked: {
        DaoVotingNativeStakedQueryClient: typeof _41.DaoVotingNativeStakedQueryClient;
        DaoVotingNativeStakedClient: typeof _41.DaoVotingNativeStakedClient;
    };
}
