/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare type Uint128 = string;
export interface InstantiateMsg {
    owner: string;
    reward_rate: Uint128;
    reward_token: string;
    staking_addr: string;
}
export declare type ExecuteMsg = {
    update_config: {
        reward_rate: Uint128;
        reward_token: string;
        staking_addr: string;
    };
} | {
    distribute: {};
} | {
    withdraw: {};
} | {
    update_ownership: Action;
};
export declare type Action = {
    transfer_ownership: {
        expiry?: Expiration | null;
        new_owner: string;
    };
} | "accept_ownership" | "renounce_ownership";
export declare type Expiration = {
    at_height: number;
} | {
    at_time: Timestamp;
} | {
    never: {};
};
export declare type Timestamp = Uint64;
export declare type Uint64 = string;
export declare type QueryMsg = {
    info: {};
} | {
    ownership: {};
};
export declare type MigrateMsg = {
    from_v1: {};
};
export declare type Addr = string;
export interface InfoResponse {
    balance: Uint128;
    config: Config;
    last_payment_block: number;
}
export interface Config {
    reward_rate: Uint128;
    reward_token: Addr;
    staking_addr: Addr;
}
export interface OwnershipForAddr {
    owner?: Addr | null;
    pending_expiry?: Expiration | null;
    pending_owner?: Addr | null;
}
