/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare type Denom = {
    native: string;
} | {
    cw20: Addr;
};
export declare type Addr = string;
export interface InstantiateMsg {
    owner?: string | null;
    reward_duration: number;
    reward_token: Denom;
    staking_contract: string;
}
export declare type ExecuteMsg = {
    stake_change_hook: StakeChangedHookMsg;
} | {
    claim: {};
} | {
    receive: Cw20ReceiveMsg;
} | {
    fund: {};
} | {
    update_reward_duration: {
        new_duration: number;
    };
} | {
    update_ownership: Action;
};
export declare type StakeChangedHookMsg = {
    stake: {
        addr: Addr;
        amount: Uint128;
    };
} | {
    unstake: {
        addr: Addr;
        amount: Uint128;
    };
};
export declare type Uint128 = string;
export declare type Binary = string;
export declare type Action = {
    transfer_ownership: {
        expiry?: Expiration | null;
        new_owner: string;
    };
} | "accept_ownership" | "renounce_ownership";
export declare type Expiration = {
    at_height: number;
} | {
    at_time: Timestamp;
} | {
    never: {};
};
export declare type Timestamp = Uint64;
export declare type Uint64 = string;
export interface Cw20ReceiveMsg {
    amount: Uint128;
    msg: Binary;
    sender: string;
}
export declare type QueryMsg = {
    info: {};
} | {
    get_pending_rewards: {
        address: string;
    };
} | {
    ownership: {};
};
export declare type MigrateMsg = {
    from_v1: {};
};
export interface PendingRewardsResponse {
    address: string;
    denom: Denom;
    last_update_block: number;
    pending_rewards: Uint128;
}
export interface InfoResponse {
    config: Config;
    reward: RewardConfig;
}
export interface Config {
    reward_token: Denom;
    staking_contract: Addr;
}
export interface RewardConfig {
    period_finish: number;
    reward_duration: number;
    reward_rate: Uint128;
}
export interface OwnershipForAddr {
    owner?: Addr | null;
    pending_expiry?: Expiration | null;
    pending_owner?: Addr | null;
}
