/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export interface InstantiateMsg {
}
export declare type ExecuteMsg = {
    instantiate_contract_with_self_admin: {
        code_id: number;
        instantiate_msg: Binary;
        label: string;
    };
};
export declare type Binary = string;
export declare type QueryMsg = string;
export interface MigrateMsg {
}
